TYPE=VIEW
query=select `uts_walia`.`mhs`.`id` AS `id`,`uts_walia`.`mhs`.`nim` AS `nim`,`uts_walia`.`mhs`.`nama_mhs` AS `nama_mhs`,`uts_walia`.`mhs`.`jenis_kelamin` AS `jenis_kelamin`,`uts_walia`.`mhs`.`alamat` AS `alamat`,`uts_walia`.`mhs`.`no_hp` AS `no_hp` from `uts_walia`.`mhs`
md5=348cf241f4c3950073237d92da1f862d
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2019-11-11 21:57:50
create-version=2
source=SELECT * FROM mhs;
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `uts_walia`.`mhs`.`id` AS `id`,`uts_walia`.`mhs`.`nim` AS `nim`,`uts_walia`.`mhs`.`nama_mhs` AS `nama_mhs`,`uts_walia`.`mhs`.`jenis_kelamin` AS `jenis_kelamin`,`uts_walia`.`mhs`.`alamat` AS `alamat`,`uts_walia`.`mhs`.`no_hp` AS `no_hp` from `uts_walia`.`mhs`
mariadb-version=100128
